### ISSUE TITLE
Anbox Cannot Connect to Internet (Linux Mint 18)

### ISSUE THREAD

**Issue by njuejohn** [anbox/anbox#157] opened 2017-04-21 04:50 UTC
Yesterday I installed Anbox on my mint box 18. Apps install and run smoothly but the web viewer will not allow me to browse the net. Kindly advise how this can be resolved.

**Comment by morphis** [comment] 2017-04-21 05:14
Duplicate of https://github.com/anbox/anbox/issues/51

**Closed by morphis** 2017-04-21 05:14 UTC

**Comment by hub2git** [comment] 2017-04-21 21:30
@njuejohn. I'm on Linux mint 18.1, too, but didn't progress as far as you.
I'm stuck on issue #40. when you launch AnBox from the mint menu, you
didn't have a problem?
Are you​ on mint 18.1 Selena​h too? Is this incident the first roadblock
you've come across?
