### ISSUE TITLE
Anbox does not launch

### ISSUE THREAD

**Issue by LTGoldman** [anbox/anbox#113] opened 2017-04-15 18:49 UTC
Tried installing on Ubuntu 17.04 64bit, when launching the app seems to crash, no errors given.

My hardware ASUS, N56VM

version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-19-generic (buildd@lcy01-13) (gcc version 6.3.0 20170321 (Ubuntu 6.3.0-10ubuntu1) ) #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Comment by JonTheNiceGuy** [comment] 2017-04-15 19:15
Confirm: Ubuntu Gnome Edition 17.04.

version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.10.0-19-generic (buildd@lcy01-13) (gcc version 6.3.0 20170321 (Ubuntu 6.3.0-10ubuntu1) ) #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

spriggsj@Minilith:~$ ps aux | grep anbox
root      1302  0.8  0.3 301108 12444 ?        Ssl  19:38   0:01 /snap/anbox/15/usr/bin/anbox container-manager --data-path=/var/snap/anbox/common/ --android-image=/snap/anbox/15/android.img
nobody    1456  0.0  0.0  49984   400 ?        S    19:38   0:00 dnsmasq -u nobody --strict-order --bind-interfaces --pid-file=/run/anbox/dnsmasq.pid --dhcp-no-override --except-interface=lo --interface=anboxbr0 --dhcp-leasefile=/var/lib/anbox/dnsmasq.anboxbr0.leases --dhcp-authoritative --listen-address 10.0.6.1 --dhcp-range 10.0.6.2,10.0.6.254 --dhcp-lease-max=252 --dhcp-range=fd9d:e4dc:4e00:9e98::1,ra-stateless,ra-names --listen-address fd9d:e4dc:4e00:9e98::1
spriggsj  2928  0.0  0.0  14240   936 pts/0    S+   19:41   0:00 grep --color=auto anbox

Interestingly, when installing it, it complains about missing upstart, so this might be part of the issue? I've just installed upstart, so we'll see if that fixes it.

**Comment by styltsars96** [comment] 2017-04-16 17:32
Tried installing on Linux Mint 18.1 64bit (Cinnamon). When  I launch the app, it seems to crash, with no errors given.
My machine specs:
Dell Latitude D830
OS: Linux Mint 18.1 Cinnamon
Desktop: Cinnamon v3.2.7
CPU: Intel Core2 Duo T7800
GPU: NVIDIA G86M [Quadro NVS 140M]

BUT after attempting starting anbox through the terminal I got some messages.

command: anbox system-info
output: Segmentation fault

command: anbox container-manager
output: [EE 2017-04-16 17:12:23] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"
comment: The entire /var/lib/anbox DIRECTORY DOES NOT EXIST actually (!!!) , which shouldn't have happened considering that I did exactly what I should when I installed anbox. Nothing irregular was shown in output , nothing irregular was done and I can say so after having read the installation script.

command: anbox version
output: anbox 0.1.0

command: anbox session-manager
no output
comment: Had to interrupt it and kill it.

command: anbox launch
comment: Needs the session manager to run

It seems the installation is somehow incomplete and there was nothing I could do about it that is outside anbox itself.

As for missing upstart, which was stated above, I got no message of that kind when installing... o.O

Hope this information has been useful! :)
Good luck!

**Comment by christianfl** [comment] 2017-04-16 21:09
I'm using Ubuntu 17.04 GNOME, too. At first I also thought that it does not work. Try to start it by typing `anbox session-manager` in the terminal and then start the Anbox application via shortcut. I'm not sure why right now but that worked for me!

**Comment by GNUGradyn** [comment] 2017-04-19 00:12
anbox session-manager just hangs, and anbox launch hangs if i run it while session-manager is hanging and eventually returns:
```
[WW 2017-04-19 00:11:49] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-04-19 00:11:49] [launch.cpp:116@operator()] with your setup and the container may have failed to boot.

```

**Comment by morphis** [comment] 2017-04-21 05:25
The original issue  described here is because we don't support the Nvidia driver yet. Duplicate of https://github.com/anbox/anbox/issues/11

**Closed by morphis** 2017-04-21 05:25 UTC
