### ISSUE TITLE
adb install fail on some apps

### ISSUE THREAD

**Issue by PhoenixGR** [anbox/anbox#78] opened 2017-04-13 12:30 UTC
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

Many apps (mostly games) while adb install reruns this : Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

Expected: to install apk.

Additional info: I know that this is some problem of compatibility with CPU of different architecture of the compiled apk but if someone has as solution for this case is welcome.

**Comment by asharptech** [comment] 2017-04-14 01:51
Make sure to get the x86 versions, from apkmirror.com or otherwise. Some Android apps just arent compatible with x86

**Comment by PhoenixGR** [comment] 2017-04-14 09:32
@asharptech  i know but not every app is x86 right ? so if some app is compiled only for ARM arent there a way to emulate and run it ?

**Comment by RubenKelevra** [comment] 2017-04-14 14:37
The main issue here is the not very descriptive error message. Maybe also a hint in the readme about this limitation would be useful, to not let new users run in this troubles as well.

@PhoenixGR this looks like a bugreport, why not open a feature request (if this does not exist already) for your emulation idea. :)

**Comment by dani0001414** [comment] 2017-04-20 14:10
AnBox executable natively the android applications not emluate the android system. So this limitations evident for ARM based application. I think in an ARM based linux OS can execute this applications, but i can't test this. :)

**Comment by subjectdenied** [comment] 2017-04-20 14:46
there is libhoudini, which is used in various projects like android-x86 and remix os for arm-emulation:
https://sourceforge.net/p/android-x86/device_generic_common/ci/66510491d170867dfd28768cd5e385fe97a7fd9a/#diff-1

**Comment by RubenKelevra** [comment] 2017-04-20 15:23
Would be nice if AnBox can add this library and print a warning while installation of an app which needs emulation. 

I tried to use Apple Music a while ago on an android emulator, but it was ARM only, so no music streaming for my Arch-Notebook :(

Hope that you get that sorted out, guys! Would be gorgeous! :)

**Comment by gilzamir** [comment] 2017-05-01 16:06
Anbox also supports arm architecture. I'm trying to create an image, if I succeed, I make the image available to everyone.

**Comment by morphis** [comment] 2017-05-01 16:11
> Anbox also supports arm architecture. I'm trying to create an image, if I succeed, I make the image available to everyone.

You should keep in mind that this image would only allow execution on ARM based platforms but not on x86 ones!

As commented on other bugs already, we don't have any plans to make emulation of these ARM based applications yet. As libhoudini is not available as Open Source we can't add it.

Closing this for now as not a bug.

**Closed by morphis** 2017-05-01 16:11 UTC

**Comment by woyaojizhu8** [comment] 2017-07-15 10:51
> As libhoudini is not available as Open Source we can't add it.
Of course you can't add it, but you can make anbox compatible with libhoudini, and give instructions on how to add libhoudini to anbox.

**Comment by zixia** [comment] 2018-06-21 03:42
+1 for make Anbox compatible with libhoudini.

Like what android-x86 does: https://stackoverflow.com/a/49684842/1123955

**Comment by jidanni** [comment] 2019-08-01 03:15
As we see on
https://www.apkmirror.com/apk/couchsurfing-inc/couchsurfing-travel-app/
in the past they offered variants, but now there is only one .apk.

**Comment by marcussacana** [comment] 2020-10-03 02:21
+1 for make Anbox compatible with libhoudini.

**Comment by avi-01** [comment] 2020-10-12 05:01
https://www.how2shout.com/linux/how-to-install-anbox-on-ubuntu-20-04-lts-focal-fossa/

This article will help you. Its has the guide to run apps. Even play store.
