### ISSUE TITLE
need option to install on archlinux

### ISSUE THREAD

**Issue by mac-linux-free** [anbox/anbox#22] opened 2017-04-11 22:28 UTC
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**

**Description of the problem:**

**Expected:**

**Additional info:**

**Comment by maxolasersquad** [comment] 2017-04-11 23:47
This is a dupe of https://github.com/anbox/anbox/issues/3

**Closed** 2017-04-12 07:07 UTC
Labels: duplicate
