### ISSUE TITLE
Can't start anbox after manjaro update

### ISSUE THREAD

**Issue by culebrasolida** [anbox/anbox#1586] opened 2020-08-25 16:03 UTC
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-c1e7550
cpu:
  arch:  x86
  brand: AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G 
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Manjaro Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.4.58-1-MANJARO (builduser@LEGION) (gcc version 10.1.0 (GCC)) #1 SMP PREEMPT Tue Aug 11 15:46:30 UTC 2020
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.2 Mesa 20.1.5
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_draw_instanced
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_AMD_performance_monitor
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_NV_pixel_buffer_object
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_EXT_window_rectangles
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_NV_alpha_to_coverage_dither_control
      - GL_EXT_EGL_image_storage
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_MESA_framebuffer_flip_y
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod

```
</details>

After a major update (also updated anbox packages from AUR) anbox is not starting anymore.
Terminal output: 
[hapushi@hapushi-manjaro ~]$ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2020-08-25 16:02:21] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.InvalidArgs] Failed to create a plain message (Invalid argument)

**What were you expecting?:**
Anbox should start properly as usual

**Additional info:**

**Comment by necessarily-equal** [comment] 2020-08-26 08:13
If you use the AUR, you need to rebuild the package from time to time when you do an upgrade, just like when you install from source. If that's the case, can you try to do that?

**Comment by alsoGAMER** [comment] 2020-09-05 15:02
I've also had issues after a major update

Using `anbox session-manager` results in this stack trace:
```
[ 2020-09-05 14:53:13] [Renderer.cpp:190@initialize] Failed: Missing egl_image related extension(s)
Stack trace (most recent call last) in thread 124889:
#7    Object "", at 0xffffffffffffffff, in 
#6    Object "/usr/lib/libc-2.32.so", at 0x7fa5959fd292, in __clone
#5    Object "/usr/lib/libpthread-2.32.so", at 0x7fa595d7c3e8, in start_thread
#4    Object "/usr/bin/anbox", at 0x55e8576ffce0, in emugl::Thread::thread_main(void*)
#3    Object "/usr/bin/anbox", at 0x55e857603982, in RenderThread::main()
#2    Object "/usr/bin/anbox", at 0x55e8576faa0e, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/usr/bin/anbox", at 0x55e8576712ee, in 
#0    Object "/usr/bin/anbox", at 0x55e857674cd5, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
zsh: segmentation fault (core dumped)  anbox session-manager
```

But using `anbox launch --package=org.anbox.appmgr` results in this error:

```[ 2020-09-05 14:58:58] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files```

**Comment by Lepidos** [comment] 2020-10-01 16:59
The same with me
` 2020-10-01 16:55:30] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files`

**Comment by necessarily-equal** [comment] 2020-10-04 08:48
@Lepidos can you try to run `anbox session-manager` manually and report 
the result? I'd say if the anbox client (`anbox launch`) can't contact 
the dbus service, it's most likely because it failed to start.

Le jeu 1 oct. 2020 à 18:59, Lepidos <notifications@github.com> a 
écrit :

**Comment by Lepidos** [comment] 2020-10-04 18:14
[anbox_session-manager.txt](https://github.com/anbox/anbox/files/5324005/anbox_session-manager.txt)

**Comment by necessarily-equal** [comment] 2020-10-05 06:33
Well, you seem to be missing /usr/share/libdrm/amdgpu.ids. That's not 
Anbox's fault. This might help if you messed with your graphics drivers 
https://askubuntu.com/questions/971343/cannot-revert-graphics-drivers-after-trying-to-upgrade-using-the-oibaf-ppa-on-ub#992654

Le dim 4 oct. 2020 à 20:15, Lepidos <notifications@github.com> a 
écrit :

**Comment by Lepidos** [comment] 2020-10-05 10:07
@necessarily-equal anbox has an issue for that, here on github. 
https://github.com/anbox/anbox/issues/1031

libdrm-amdgpu1 debian package is installed on my system...

**Comment by Zokemore** [comment] 2021-01-04 03:42
Despite rebuilding anbox from source, anbox keeps crashing after update on arch linux.

zokemore@arch ~]$ anbox session-manager
[ 2021-01-04 03:40:48] [client.cpp:48@start] Failed to start container: Failed to start container: Failed to start container
[ 2021-01-04 03:40:48] [session_manager.cpp:161@operator()] Lost connection to container manager, terminating.
[ 2021-01-04 03:40:48] [daemon.cpp:61@Run] Container is not running
[ 2021-01-04 03:40:48] [session_manager.cpp:161@operator()] Lost connection to container manager, terminating.
Stack trace (most recent call last) in thread 3146:
#7    Object "", at 0xffffffffffffffff, in


[zokemore@arch ~]$ anbox system-info
version: local-6c10125
cpu:
  arch:  x86
  brand: AMD A9-9425 RADEON R5, 5 COMPUTE CORES 2C+3G   
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Arch Linux
  version: 
  snap-based: false
kernel:
  version: Linux version 5.10.3-zen1-1-zen (linux-zen@archlinux) (gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 ZEN SMP PREEMPT Sun, 27 Dec 2020 12:04:22 +0000
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_EXT_swap_buffers_with_damage
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_swap_buffers_with_damage
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: AMD
    vendor: OpenGL ES 3.2 Mesa 20.3.2
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_draw_instanced
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_AMD_performance_monitor
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_OES_viewport_array
      - GL_ANGLE_pack_reverse_row_order
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_NV_pixel_buffer_object
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_implicit_conversions
      - GL_EXT_shader_integer_mix
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_ANDROID_extension_pack_es31a
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_gpu_shader5
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_render_snorm
      - GL_EXT_shader_io_blocks
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_norm16
      - GL_EXT_texture_view
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_robust_buffer_access_behavior
      - GL_NV_image_formats
      - GL_OES_copy_image
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_gpu_shader5
      - GL_OES_primitive_bounding_box
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_texture_view
      - GL_EXT_blend_func_extended
      - GL_EXT_buffer_storage
      - GL_EXT_float_blend
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_shader_samples_identical
      - GL_KHR_no_error
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_OES_EGL_image_external_essl3
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_shader_image_atomic
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_EXT_window_rectangles
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_EXT_color_buffer_half_float
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_EXT_semaphore
      - GL_EXT_semaphore_fd
      - GL_EXT_texture_compression_bptc
      - GL_KHR_parallel_shader_compile
      - GL_NV_alpha_to_coverage_dither_control
      - GL_AMD_framebuffer_multisample_advanced
      - GL_EXT_EGL_image_storage
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_INTEL_blackhole_render
      - GL_MESA_framebuffer_flip_y
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod




[ zokemore@arch ~] $ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2021-01-04 03:25:36] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files

[ zokemore@arch ~] $ systemctl status anbox-container-manager.service
* anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; e>
     Active: active (running) since Mon 2021-01-04 08:33:03 IST; 33min ago
   Main PID: 441 (anbox)
      Tasks: 0 (limit: 4531)
     Memory: 15.3M
     CGroup: /system.slice/anbox-container-manager.service
             > 441 /usr/bin/anbox container-manager --daemon --privileged --dat>

Jan 04 08:33:03 chord systemd[1]: Started Anbox Container Manager.

libdrm is installed & amdgpu is loaded in mkiitcpio. Kindly suggest solution.

**Comment by Zokemore** [comment] 2021-01-08 04:28
An more detailed log found when running 'anbox session-manager'

[zokemore@arch ~]$ anbox session-manager
[ 2021-01-08 04:21:51] [client.cpp:48@start] Failed to start container: Failed to start container: Failed to start container
[ 2021-01-08 04:21:51] [session_manager.cpp:161@operator()] Lost connection to container manager, terminating.
[ 2021-01-08 04:21:52] [daemon.cpp:61@Run] Container is not running
[ 2021-01-08 04:21:52] [session_manager.cpp:161@operator()] Lost connection to container manager, terminating.
Stack trace (most recent call last) in thread 3441:
#7    Object "", at 0xffffffffffffffff, in 
#6    Object "/usr/lib/libc-2.32.so", at 0x7f9d9037a292, in __clone
#5    Object "/usr/lib/libpthread-2.32.so", at 0x7f9d907433e8, in start_thread
#4    Source "/build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc", line 80, in execute_native_thread_routine [0x7f9d90539c23]
#3    Object "/usr/bin/anbox", at 0x55b672a07c85, in 
#2    Object "/usr/bin/anbox", at 0x55b67299e8d0, in boost::asio::detail::scheduler::run(boost::system::error_code&)
#1    Object "/usr/bin/anbox", at 0x55b672a33432, in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)>, boost::asio::execution::any_executor<boost::asio::execution::context_as_t<boost::asio::execution_context&>, boost::asio::execution::detail::blocking::never_t<0>, boost::asio::execution::prefer_only<boost::asio::execution::detail::blocking::possibly_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::tracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::outstanding_work::untracked_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::fork_t<0> >, boost::asio::execution::prefer_only<boost::asio::execution::detail::relationship::continuation_t<0> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)
#0    Object "/usr/bin/anbox", at 0x55b6729937a6, in 
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

**Comment by sevu** [comment] 2021-01-08 09:23
Sounds like https://wiki.archlinux.org/index.php/Linux_Containers#Incompatibility_with_linux_kernel_5.10.0

Seems to be fixed by 5.10.4, which is in the Arch repos by now.

**Comment by necessarily-equal** [comment] 2021-01-08 09:33
Someone on telegram reported seeing it on Linux Mint 20.0.

`uname -a`: `Linux gokul-Lenovo-E41-25 5.4.0-58-generic #64-Ubuntu SMP 
Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Zokemore** [comment] 2021-01-09 06:55
> Sounds like https://wiki.archlinux.org/index.php/Linux_Containers#Incompatibility_with_linux_kernel_5.10.0
> 
> Seems to be fixed by 5.10.4, which is in the Arch repos by now.

Thank you for your support. Issue resolved with lxc replaced by lxc-git. I'm running zen version of the arch kernel which is still at 5.10.3  which is probably reason for issue. However issue can be also be partially fixed by switching to lts version of kernel 5.4 where it works fine even without lxc-git. 
I hope issue is fixed others as well.

**Comment by lucasfcnunes** [comment] 2021-02-16 17:22
Try:
```export EGL_PLATFORM=x11```

**Comment by chenzaichun** [comment] 2021-02-19 03:56
> Try:
> `export EGL_PLATFORM=x11`

This works on ubuntu 20.04 with gnome on wayland. Thanks.

**Comment by necessarily-equal** [comment] 2021-02-19 11:48
works on Ubuntu 20.04 with GNOME on X.org too

**Comment by fsevenm** [comment] 2021-02-27 00:01
> Try:
> `export EGL_PLATFORM=x11`

It really works. Anybody can explain why this works?

I tried to build anbox from source (using snapcraft), waited about 6 hours for it to complete, faced too many issues including multipass errors (about 3 days to fix them until successful built). Then after that, just could not run anbox due to the error (below). I almost got frustrated. With a little patience left,  I searched in the issue keyword related to that, found this issue. Tried `export EGL_PLATFORM=x11` before `anbox.appmgr` and boom, it just run. I felt my 4 days of exploration got paid.

```sh
❯ anbox.appmgr 
[ 2021-02-26 23:39:58] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
```

Note:
When getting that error, I checked anbox container manager service was working pretty well.
On Ubuntu 18.04

**Comment by qiujiangkun** [comment] 2021-04-12 16:53
> Try:
> `export EGL_PLATFORM=x11`

Not working for me. 5.10.23-1-MANJARO

**Comment by necessarily-equal** [comment] 2021-04-12 17:06
you can try to add SDL_PLATFORM=x11 too. Also, note that you must start 
Anbox (specifically, `anbox session-manager`) from the same terminal.

**Comment by qiujiangkun** [comment] 2021-04-12 17:21
Still not working
```log
➜  ~ anbox session-manager                
[ 2021-04-12 17:14:18] [session_manager.cpp:149@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
➜  ~ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2021-04-12 17:15:15] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
➜  ~ export https_proxy=socks5://127.0.0.1:8092
➜  ~ export SDL_PLATFORM=x11                   
➜  ~ export EGL_PLATFORM=x11                                                        
➜  ~ anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
[ 2021-04-12 17:19:59] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
➜  ~ systemctl status anbox-container-manager.service
● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/usr/lib/systemd/system/anbox-container-manager.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
➜  ~ sudo systemctl start anbox-container-manager.service
[sudo] password for jack: 
➜  ~ anbox session-manager                                                               
[ 2021-04-12 17:21:05] [session_manager.cpp:149@operator()] Failed to start as either binder or ashmem kernel drivers are not loaded
```

**Comment by plata** [comment] 2021-05-23 13:30
In case someone else also has issues figuring out how **exactly** to use the advice from @lucasfcnunes:
```
sudo pacman -S anbox anbox-image
export EGL_PLATFORM=x11
sudo systemctl start anbox-container-manager
anbox launch --package=org.anbox.appmgr --component=org.anbox.appmgr.AppViewActivity
```

**Comment by atom7890** [comment] 2021-06-21 17:10
> Try:
> `export EGL_PLATFORM=x11`

thanks

**Comment by KaKi87** [comment] 2021-07-06 08:22
I'm encountering the same issue and this workaround works, although I wonder why this almost one year old issue hasn't been properly fixed yet...

**Comment by Fuseteam** [comment] 2021-07-06 15:58
@KaKi87 probably because nobody knows why it happens/what the cause is

**Comment by amadu80** [comment] 2021-07-10 09:57
Executing the command ``export EGL_PLATFORM=x11 does work for me. Although, if you don't want to do that every time, just add that variable to the `/etc/environment`

`sudo vi /etc/environment`
then to the file
append `EGL_PLATFORM=x11`

In my case the ``/etc/environment` has:
`PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
EGL_PLATFORM=x11
`

**Comment by verenzuela** [comment] 2021-08-08 19:47
This script will collect a few interesting things which developers will
need to have a better insight into the Anbox system when something goes
wrong.

PLEASE NOTE: The collected log files may collect information about your
system. Please have a look before you're sending them to anyone!

Collecting anbox log files ... 
+ cp /var/snap/anbox/common/data/system.log /tmp/tmp.VzojLTK89j
cp: cannot stat '/var/snap/anbox/common/data/system.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/containers/lxc-monitord.log /tmp/tmp.VzojLTK89j
cp: cannot stat '/var/snap/anbox/common/containers/lxc-monitord.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/container.log /tmp/tmp.VzojLTK89j
cp: cannot stat '/var/snap/anbox/common/logs/container.log': No such file or directory
+ true
+ cp /var/snap/anbox/common/logs/console.log* /tmp/tmp.VzojLTK89j
cp: cannot stat '/var/snap/anbox/common/logs/console.log*': No such file or directory
+ true
+ /snap/anbox/213/command-anbox.wrapper system-info
+ true
+ [ -e /etc/systemd/system/snap.anbox.container-manager.service ]
+ sudo journalctl --no-pager -u snap.anbox.container-manager.service
+ set +x

DONE!

Do you want to include the kernel log of your system? [y/N]
y
+ dmesg
+ set +x
Generating archive with all log files in /usr/src ...
  adding: container-manager.log (deflated 91%)
  adding: kernel.log (deflated 76%)
  adding: system-info.log (deflated 16%)
DONE!

Now please take the ZIP archive generated in your current directory
and attach it to your bug report. Please don't hesitate to have a
look into the archive before you do so to verify you don't leak any
information you don't want!

**Closed** 2022-04-28 19:06 UTC
Labels: decaying
