### ISSUE TITLE
No Internet

### ISSUE THREAD

**Issue by AEAEAEAE4343** [anbox/anbox#560] opened 2017-12-26 23:17 UTC
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
[version: 3
snap-revision: 65
os:
  name: Ubuntu
  version: 17.10 (Artful Aardvark)
  snap-based: true
kernel:
  version: Linux version 4.13.0-21-generic (buildd@lgw01-amd64-037) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: nouveau
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
]
```

**Please describe your problem:**
I have no internet connection with android applications on anbox

**What were you expecting?:**
Android apps to have internet

**Additional info:**

**Comment by NeoTheThird** [comment] 2017-12-30 23:43
I can confirm this. Running `adb shell` and `ping 8.8.8.8` prints network unreachable.

**Comment by chocholo** [comment] 2017-12-31 05:48
I can see the same issue when using current master. In Settings I can't see any network devices and in "adb shell ip a l" there is only loopback device.

**Comment by NeoTheThird** [comment] 2018-01-01 12:27
duplicate of https://github.com/anbox/anbox/issues/443. see https://github.com/anbox/anbox/issues/443#issuecomment-345449671 for a workaround.

**Closed** 2018-09-15 17:36 UTC
Labels: decaying

**Comment by lfxyl** [comment] 2018-09-23 07:16
I have this problem too.This is my ```anbox system-info```:
version: 4
snap-revision: 154
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-34-generic (buildd@lgw01-amd64-047) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array

**Comment by pramodhrachuri** [comment] 2019-01-31 05:40
I too have this problem. My `anbox system-info` is as the following.
`version: 4
snap-revision: 158
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.15.0-43-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.2 Mesa 18.0.5
    extensions:
      - GL_ANDROID_extension_pack_es31a
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_disjoint_timer_query
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_framebuffer_fetch
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_shader_samples_identical
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_INTEL_conservative_rasterization
      - GL_INTEL_performance_query
      - GL_KHR_blend_equation_advanced
      - GL_KHR_blend_equation_advanced_coherent
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_KHR_texture_compression_astc_ldr
      - GL_KHR_texture_compression_astc_sliced_3d
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
`

**Comment by Anlarry** [comment] 2019-12-24 05:41
I too have this problem. My ‘anbox system-info’ is as the following
    version: local-0a49ae0
    cpu:
    arch:  x86
    brand: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    features: 
        - aes
        - sse4_1
        - sse4_2
        - avx
        - avx2
    os:
    name: Manjaro Linux
    version: 
    snap-based: false
    kernel:
    version: Linux version 5.3.15-1-MANJARO (builduser@development) (gcc version 9.2.0 (GCC)) #1 SMP PREEMPT Thu Dec 5 11:01:29 UTC 2019
    binder: true
    ashmem: true
    graphics:
    egl:
        vendor: Mesa Project
        version: 1.4
        extensions:
        - EGL_ANDROID_blob_cache
        - EGL_ANDROID_native_fence_sync
        - EGL_CHROMIUM_sync_control
        - EGL_EXT_buffer_age
        - EGL_EXT_create_context_robustness
        - EGL_EXT_image_dma_buf_import
        - EGL_EXT_image_dma_buf_import_modifiers
        - EGL_IMG_context_priority
        - EGL_KHR_config_attribs
        - EGL_KHR_create_context
        - EGL_KHR_create_context_no_error
        - EGL_KHR_fence_sync
        - EGL_KHR_get_all_proc_addresses
        - EGL_KHR_gl_colorspace
        - EGL_KHR_gl_renderbuffer_image
        - EGL_KHR_gl_texture_2D_image
        - EGL_KHR_gl_texture_3D_image
        - EGL_KHR_gl_texture_cubemap_image
        - EGL_KHR_image
        - EGL_KHR_image_base
        - EGL_KHR_image_pixmap
        - EGL_KHR_no_config_context
        - EGL_KHR_reusable_sync
        - EGL_KHR_surfaceless_context
        - EGL_EXT_pixel_format_float
        - EGL_KHR_wait_sync
        - EGL_MESA_configless_context
        - EGL_MESA_drm_image
        - EGL_MESA_image_dma_buf_export
        - EGL_MESA_query_driver
        - EGL_NOK_texture_from_pixmap
        - EGL_WL_bind_wayland_display
    gles2:
        vendor: Intel Open Source Technology Center
        vendor: OpenGL ES 3.2 Mesa 19.2.7
        extensions:
        - GL_EXT_blend_minmax
        - GL_EXT_multi_draw_arrays
        - GL_EXT_texture_filter_anisotropic
        - GL_EXT_texture_compression_s3tc
        - GL_EXT_texture_compression_dxt1
        - GL_EXT_texture_compression_rgtc
        - GL_EXT_texture_format_BGRA8888
        - GL_OES_compressed_ETC1_RGB8_texture
        - GL_OES_depth24
        - GL_OES_element_index_uint
        - GL_OES_fbo_render_mipmap
        - GL_OES_mapbuffer
        - GL_OES_rgb8_rgba8
        - GL_OES_standard_derivatives
        - GL_OES_stencil8
        - GL_OES_texture_3D
        - GL_OES_texture_float
        - GL_OES_texture_float_linear
        - GL_OES_texture_half_float
        - GL_OES_texture_half_float_linear
        - GL_OES_texture_npot
        - GL_OES_vertex_half_float
        - GL_EXT_texture_sRGB_decode
        - GL_OES_EGL_image
        - GL_OES_depth_texture
        - GL_OES_packed_depth_stencil
        - GL_EXT_texture_type_2_10_10_10_REV
        - GL_NV_conditional_render
        - GL_OES_get_program_binary
        - GL_APPLE_texture_max_level
        - GL_EXT_discard_framebuffer
        - GL_EXT_read_format_bgra
        - GL_EXT_frag_depth
        - GL_NV_fbo_color_attachments
        - GL_OES_EGL_image_external
        - GL_OES_EGL_sync
        - GL_OES_vertex_array_object
        - GL_OES_viewport_array
        - GL_ANGLE_texture_compression_dxt3
        - GL_ANGLE_texture_compression_dxt5
        - GL_EXT_occlusion_query_boolean
        - GL_EXT_robustness
        - GL_EXT_texture_rg
        - GL_EXT_unpack_subimage
        - GL_NV_draw_buffers
        - GL_NV_read_buffer
        - GL_NV_read_depth
        - GL_NV_read_depth_stencil
        - GL_NV_read_stencil
        - GL_EXT_draw_buffers
        - GL_EXT_map_buffer_range
        - GL_KHR_debug
        - GL_KHR_robustness
        - GL_KHR_texture_compression_astc_ldr
        - GL_OES_depth_texture_cube_map
        - GL_OES_required_internalformat
        - GL_OES_surfaceless_context
        - GL_EXT_color_buffer_float
        - GL_EXT_sRGB_write_control
        - GL_EXT_separate_shader_objects
        - GL_EXT_shader_framebuffer_fetch
        - GL_EXT_shader_implicit_conversions
        - GL_EXT_shader_integer_mix
        - GL_EXT_tessellation_point_size
        - GL_EXT_tessellation_shader
        - GL_INTEL_conservative_rasterization
        - GL_INTEL_performance_query
        - GL_ANDROID_extension_pack_es31a
        - GL_EXT_base_instance
        - GL_EXT_compressed_ETC1_RGB8_sub_texture
        - GL_EXT_copy_image
        - GL_EXT_draw_buffers_indexed
        - GL_EXT_draw_elements_base_vertex
        - GL_EXT_gpu_shader5
        - GL_EXT_polygon_offset_clamp
        - GL_EXT_primitive_bounding_box
        - GL_EXT_render_snorm
        - GL_EXT_shader_io_blocks
        - GL_EXT_texture_border_clamp
        - GL_EXT_texture_buffer
        - GL_EXT_texture_cube_map_array
        - GL_EXT_texture_norm16
        - GL_EXT_texture_view
        - GL_KHR_blend_equation_advanced
        - GL_KHR_blend_equation_advanced_coherent
        - GL_KHR_context_flush_control
        - GL_KHR_robust_buffer_access_behavior
        - GL_NV_image_formats
        - GL_OES_copy_image
        - GL_OES_draw_buffers_indexed
        - GL_OES_draw_elements_base_vertex
        - GL_OES_gpu_shader5
        - GL_OES_primitive_bounding_box
        - GL_OES_sample_shading
        - GL_OES_sample_variables
        - GL_OES_shader_io_blocks
        - GL_OES_shader_multisample_interpolation
        - GL_OES_tessellation_point_size
        - GL_OES_tessellation_shader
        - GL_OES_texture_border_clamp
        - GL_OES_texture_buffer
        - GL_OES_texture_cube_map_array
        - GL_OES_texture_stencil8
        - GL_OES_texture_storage_multisample_2d_array
        - GL_OES_texture_view
        - GL_EXT_blend_func_extended
        - GL_EXT_buffer_storage
        - GL_EXT_float_blend
        - GL_EXT_geometry_point_size
        - GL_EXT_geometry_shader
        - GL_EXT_shader_samples_identical
        - GL_KHR_no_error
        - GL_KHR_texture_compression_astc_sliced_3d
        - GL_NV_fragment_shader_interlock
        - GL_OES_EGL_image_external_essl3
        - GL_OES_geometry_point_size
        - GL_OES_geometry_shader
        - GL_OES_shader_image_atomic
        - GL_EXT_clip_cull_distance
        - GL_EXT_disjoint_timer_query
        - GL_EXT_texture_compression_s3tc_srgb
        - GL_MESA_shader_integer_functions
        - GL_EXT_clip_control
        - GL_EXT_texture_compression_bptc
        - GL_KHR_parallel_shader_compile
        - GL_EXT_shader_framebuffer_fetch_non_coherent
        - GL_EXT_texture_sRGB_R8
        - GL_EXT_texture_shadow_lod
        - GL_MESA_framebuffer_flip_y
        - GL_NV_compute_shader_derivatives
        - GL_EXT_depth_clamp
        - GL_EXT_texture_query_lod

**Comment by phrogg** [comment] 2021-11-23 18:40
Same here
