### ISSUE TITLE
Andbox under Ubuntu :pb iapk install

### ISSUE THREAD

**Issue by miraceti** [anbox/anbox#742] opened 2018-06-03 09:17 UTC
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```

**Please describe your problem:**
this error appear when i try to install VLC or MX video players by this command line : 
adb install media/eric/GLIESE/AS/apk/vlc-for-android-2-9-1.apk

the only apk i can install is the HDStreamz one

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment] 2018-06-03 10:52
@miraceti The APK you're trying to install does not support x86_64 but most likely only ARM. So there is nothing Anbox can do. There might be x86 versions of VLC available though.

Closing as this is not a bug in Anbox.

**Closed by morphis** 2018-06-03 10:52 UTC
