### ISSUE TITLE
build error in Arch Linux

### ISSUE THREAD

**Issue by pingplug** [anbox/anbox#1834] opened 2021-06-15 01:34 UTC
gcc version 11.1.0 (GCC) 

```
[ 73%] Building CXX object src/CMakeFiles/anbox-core.dir/anbox/input/manager.cpp.o
In file included from /tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:18:
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:38:8: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
   38 |   std::uint32_t next_id();
      |        ^~~~~~~~
      |        wint_t
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:39:44: error: 'uint32_t' in namespace 'std' does not name a type; did you mean 'wint_t'?
   39 |   std::string build_device_path(const std::uint32_t &id);
      |                                            ^~~~~~~~
      |                                            wint_t
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:42:17: error: 'uint32_t' is not a member of 'std'; did you mean 'wint_t'?
   42 |   std::map<std::uint32_t, std::shared_ptr<Device>> devices_;
      |                 ^~~~~~~~
      |                 wint_t
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:42:49: error: template argument 1 is invalid
   42 |   std::map<std::uint32_t, std::shared_ptr<Device>> devices_;
      |                                                 ^~
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:42:49: error: template argument 3 is invalid
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:42:49: error: template argument 4 is invalid
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp: In member function 'std::shared_ptr<anbox::input::Device> anbox::input::Manager::create_device()':
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:39:19: error: 'next_id' was not declared in this scope
   39 |   const auto id = next_id();
      |                   ^~~~~~~
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:42:12: error: request for member 'insert' in '((anbox::input::Manager*)this)->anbox::input::Manager::devices_', which is of non-class type 'int'
   42 |   devices_.insert({id, device});
      |            ^~~~~~
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp: At global scope:
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:46:15: error: no declaration matches 'uint32_t anbox::input::Manager::next_id()'
   46 | std::uint32_t Manager::next_id() {
      |               ^~~~~~~
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:46:15: note: no functions named 'uint32_t anbox::input::Manager::next_id()'
In file included from /tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:18:
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:30:7: note: 'class anbox::input::Manager' defined here
   30 | class Manager {
      |       ^~~~~~~
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:51:13: error: no declaration matches 'std::string anbox::input::Manager::build_device_path(const uint32_t&)'
   51 | std::string Manager::build_device_path(const std::uint32_t &id) {
      |             ^~~~~~~
In file included from /tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.cpp:18:
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:39:15: note: candidate is: 'std::string anbox::input::Manager::build_device_path(const int&)'
   39 |   std::string build_device_path(const std::uint32_t &id);
      |               ^~~~~~~~~~~~~~~~~
/tmp/makepkg/anbox-git/src/anbox/src/anbox/input/manager.h:30:7: note: 'class anbox::input::Manager' defined here
   30 | class Manager {
      |       ^~~~~~~
make[2]: *** [src/CMakeFiles/anbox-core.dir/build.make:1002: src/CMakeFiles/anbox-core.dir/anbox/input/manager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1682: src/CMakeFiles/anbox-core.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```

**Comment by parona-source** [comment] 2021-06-16 12:55
This is due to header changes in GCC11, you just need to add the correct header and it compiles fine. I use this patch on Gentoo.

```diff
diff --git a/src/anbox/input/manager.h b/src/anbox/input/manager.h
index 22f1406..578d02f 100644
--- a/src/anbox/input/manager.h
+++ b/src/anbox/input/manager.h
@@ -18,6 +18,7 @@
 #ifndef ANBOX_INPUT_MANAGER_H_
 #define ANBOX_INPUT_MANAGER_H_

+#include <cstdint>
 #include <map>
 #include <memory>

```

**Comment by ahmubashshir** [comment] 2021-06-17 05:24
@parona-source 
> (Although its possible that the above patch is incorrect, currently getting segfaults but i think they are unrelated to this as all tests succeed so possibly something in my env is wrong)

I think it's caused by #1801

**Comment by ChristophSchmidpeter** [comment] 2021-07-17 08:46
PR #1837 seems to address the issue, but hasn't been merged yet.

**Closed** 2022-04-28 07:07 UTC
Labels: decaying
