### ISSUE TITLE
Error building from master 

### ISSUE THREAD

**Issue by Kuchiriel** [anbox/anbox#1102] opened 2019-04-09 16:26 UTC
> .cpp:208:43: error: ‘NewCallback’ is not a member of ‘google::protobuf’
>                          google::protobuf::NewCallback(

Fixed adding some includes.

`#include <google/protobuf/stubs/callback.h>`

**Comment by barzamin** [comment] 2019-04-09 21:23
Duplicate of #1071

**Closed** 2019-04-11 01:30 UTC
