### ISSUE TITLE
The name org.anbox was not provided by any .service files

### ISSUE THREAD

**Issue by Kushagra-Srivastava** [anbox/anbox#1889] opened 2021-08-21 05:23 UTC
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `
[anbox-system-diagnostics-2021-08-21.zip](https://github.com/anbox/anbox/files/7024915/anbox-system-diagnostics-2021-08-21.zip)

6. ** Please paste the result of `anbox system-info` below:**
<details>
<summary>anbox system-info output</summary>

```
version: local-ad377ff
snap-revision: 213
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
    - avx2
os:
  name: Ubuntu
  version: 20.04.3 LTS (Focal Fossa)
  snap-based: true
kernel:
  version: Linux version 5.11.0-27-generic (buildd@lcy01-amd64-019) (gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #29~20.04.1-Ubuntu SMP Wed Aug 11 15:58:17 UTC 2021
  binder: false
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_IMG_context_priority
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

```
</details>

**Please describe your problem:**
When i am trying to run `anbox.appmgr`
It is giving this error-

`[ 2021-08-21 05:16:53] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files`

**What were you expecting?:**
Was expecting a cool anbox window

**Additional info:**
It was working fine for 3 to 4 days but now this problem or bug or issue or error or whatever popped.
I had installed it with the command ` sudo snap install --devmode --edge anbox`
I am on Ubuntu 20.04 LTS 
For `snap info anbox`
It is giving this info--

```
name:      anbox
summary:   Android in a Box
publisher: Simon Fels (morphis)
store-url: https://snapcraft.io/anbox
contact:   https://anbox.io
license:   unset
description: |
  Runtime for Android applications which runs a full Android system
  in a container using Linux namespaces (user, ipc, net, mount) to
  separate the Android system fully from the host.
  
  You can find further details in our documentation at
  https://github.com/anbox/anbox/blob/master/README.md
commands:
  - anbox
  - anbox.android-settings
  - anbox.appmgr
  - anbox.collect-bug-info
  - anbox.shell
services:
  anbox.container-manager: simple, enabled, active
snap-id:      Nr9K6UJaIOD8wHpDEQl16nabFFt9LLEQ
tracking:     latest/edge
refresh-date: today at 10:39 IST
channels:
  latest/stable:    --                                   
  latest/candidate: --                                   
  latest/beta:      4-56c25f1     2020-01-02 (186) 391MB devmode
  latest/edge:      4+gitrad377ff 2021-05-27 (213) 405MB devmode
installed:          4+gitrad377ff            (213) 405MB devmode


```
`anbox session-manager` output

```
[ 2021-08-24 10:35:08] [Renderer.cpp:128@initialize] Failed to select EGL configuration
Stack trace (most recent call last) in thread 14628:
#7    Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#6    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7fb15af73292, in clone
#5    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7fb15b2e4608, in 
#4    Object "/snap/anbox/213/usr/bin/anbox", at 0x55775608f314, in emugl::Thread::thread_main(void*)
#3    Object "/snap/anbox/213/usr/bin/anbox", at 0x557755f9b358, in RenderThread::main()
#2    Object "/snap/anbox/213/usr/bin/anbox", at 0x55775608a060, in renderControl_decoder_context_t::decode(void*, unsigned long, IOStream*)
#1    Object "/snap/anbox/213/usr/bin/anbox", at 0x557756009562, in 
#0    Object "/snap/anbox/213/usr/bin/anbox", at 0x55775600c429, in RendererConfigList::getPackInfo(int*, int*) const
Segmentation fault (Address not mapped to object [(nil)])
Segmentation fault (core dumped)

```

**Comment by Kushagra-Srivastava** [comment] 2021-08-21 05:26
someone help me please

**Comment by Kushagra-Srivastava** [comment] 2021-08-24 10:43
@kcpr  Ok I will check...

**Comment by Kushagra-Srivastava** [comment] 2021-08-24 10:46
> Try launching a manager with `EGL_PLATFORM=x11 anbox.appmgr`. More information is provided here: #1865 .

Literally no output is coming nor anbox is launching!!!

**Comment by Kushagra-Srivastava** [comment] 2021-08-25 02:04
`The name org.anbox was not provided by any .service files`
i made a bash script as i could not memorise` EGL_PLATFORM=x11 anbox.appmgr` but it shows this again `The name org.anbox was not provided by any .service files`

**Comment by Fuseteam** [comment] 2021-08-25 07:29
> > Try launching a manager with `EGL_PLATFORM=x11 anbox.appmgr`. More information is provided here: #1865 .
> 
> Literally no output is coming nor anbox is launching!!!

Run `EGL_PLATFORM=x11 anbox session-manager` no output is good output
Leave that running and launch anbox normally

**Comment by Kushagra-Srivastava** [comment] 2021-08-28 03:52
when i run `EGL_PLATFORM=x11 anbox session-manager` but no output is coming so i opened another terminal at same time an ran `EGL_PLATFORM=x11 anbox.appmgr` but output is  `[ 2021-08-28 03:49:56] [launch.cpp:202@operator()] Session manager failed to become ready`

**Comment by Fuseteam** [comment] 2021-08-28 15:01
if you get no output out of session-manager that is good. leave that running and launch anbox normally via your desktop launcher

**Comment by Kushagra-Srivastava** [comment] 2021-09-01 03:04
`[ 2021-09-01 03:03:51] [daemon.cpp:61@Run] Failed to connect to socket /var/snap/anbox/common/sockets/anbox-container.socket: Connection refused
`

**Comment by Fuseteam** [comment] 2021-09-01 14:23
@Kushagra-Srivastava that sounds like container-manager is not running, how did you install anbox again?

**Comment by Kushagra-Srivastava** [comment] 2021-09-02 09:19
i installed with snap (edge version)

**Comment by kcpr** [comment] 2021-09-03 14:12
I think I usually experience "Session manager failed to become ready" error and then, when right after it I run the same command again, the Anbox launches correctly. I would give it a try.

**Comment by kcpr** [comment] 2021-09-03 14:19
I would try runnning `snap disable anbox && snap enable anbox` and then retry.

I think I usually experience "Session manager failed to become ready" error, so it looks like a progress to me. When I experiance that error I just try to run the same command again and Anbox launches correctly. I think it's practically the same as what Fuseteam suggested.

**Comment by Fuseteam** [comment] 2021-09-03 17:19
sounds good @Kushagra-Srivastava try what kcpr suggested

**Comment by mcarans** [comment] 2021-09-16 18:08
I had this error and `EGL_PLATFORM=x11 anbox.appmgr` got rid of the error for me (on Linux Mint 20.2).

**Comment by Fuseteam** [comment] 2021-09-16 18:16
cool perhaps this [systemd user service](https://github.com/Fuseteam/systemd-service-files/blob/main/anbox-session-manager.service) could help simplify that

**Comment by Noah-It-All** [comment] 2021-10-29 21:27
> I had this error and `EGL_PLATFORM=x11 anbox.appmgr` got rid of the error for me (on Linux Mint 20.2).

Thank You, works for me (Kali Linux 2021.3)

**Comment by qaqak** [comment] 2021-12-29 14:12
Anbox for me isn't working. PERIOD!
The DKMS modules won't install!!
SOMEONE HELP :(

**Comment by Fuseteam** [comment] 2021-12-29 15:56
@qaqak not enough information PERIOD!
please provide the relevant information that we need to help.
If your using ubuntu you don't need the DKMS modules PERIOD!

**Comment by crass** [comment] 2022-01-21 23:23
I'm running Ubuntu 20.04, **not a fresh install**, with the 5.13 oem kernel. I ran into this issue as well. And this thread helped me to resolve it. For starters, `anbox system-info` shows `binder: false`, even though I have the binder module loaded (but no /dev/binder) and `binder` is in `/proc/filesystem`.

After enabling debug output, here's the error reproduced.
```
$ anbox.appmgr
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2022-01-21 23:01:27] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2022-01-21 23:01:27] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2022-01-21 23:01:27] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2022-01-21 23:01:33] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files
```

Adding `EGL_PLATFORM=x11` shows a different error
```
$ EGL_PLATFORM=x11 anbox.appmgr
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2022-01-21 23:01:40] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2022-01-21 23:01:40] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2022-01-21 23:01:40] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2022-01-21 23:02:30] [launch.cpp:202@operator()] Session manager failed to become ready
```

Starting the session manager first solves the issue and the app manager window displays
```
$ (set -x; export EGL_PLATFORM=x11; anbox session-manager & sleep 10; anbox.appmgr )
+ export EGL_PLATFORM=x11
+ EGL_PLATFORM=x11
+ sleep 10
+ anbox session-manager
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
+ anbox.appmgr
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
[ 2022-01-21 23:12:23] [application_manager_client.cpp:22@TryLaunch] Sending launch intent [ package=org.anbox.appmgr component=org.anbox.appmgr.AppViewActivity ] to Android ..
```

So (for me) this issue seem to be first that anbox doesn't detect that I'm using x11 and automatically set `EGL_PLATFORM`. Second, `anbox.appmgr` seems to not be able to successfully start the session manager. After closing `anbox.appmgr`, the session manager stays running as a user service. That may explain why some people claim that only `EGL_PLATFORM=x11 anbox.appmgr` is necessary (or `anbox.appmgr` may be successfully starting the session manager for them).

**Comment by Fuseteam** [comment] 2022-01-22 00:15
for `binder:false` please run `mkdir /dev/binder ; mount -t binder binder /dev/binder`
if you are sure `EGL_PLATFORM=x11` is both not set and needed this systemd service file might help you: github.com/fuseteam/systemd-service-files

**Comment by stefan123t** [comment] 2022-01-27 19:45
@Fuseteam thanks for your helpful answers. After executing the steps @crass suggested to keep the anbox session-manager running in the background (&) and only then start the anbox appmgr. I came here for the original error message `The name org.anbox was not provided by any .service files` was also shown on my Linux Mint 20.1 Ulyssa with linux kernel 5.11.0-41-generic. Actually also here the ashmem and binder kernel modules were present and I only had to fix the binder:false as you suggested in your previous comment.

**Comment by Fuseteam** [comment] 2022-01-27 19:54
fwiw `The name org.anbox was not provided by any .service files` is an harmless error. it should work fine despite it

**Comment by rmikedown** [comment] 2022-02-01 16:13
> for `binder:false` please run `mkdir /dev/binder ; mount -t binder binder /dev/binder` if you are sure `EGL_PLATFORM=x11` is both not set and needed this systemd service file might help you: https://github.com/fuseteam/systemd-service-files

Hey Fuseteam,

I'm dealing with the same issues with the session manager no longer loading on boot (I installed it 2 days ago and it worked at first). I can get anbox to launch without crashing only if I run EGL_PLATFORM=x11 anbox session-manager in the terminal now.

I would think I'm a good candidate to be using your solution but I get this output 

```
anbox-session-manager.service - Anbox Session Manager
     Loaded: loaded (/etc/xdg/systemd/user/anbox-session-manager.service; disab>
     Active: inactive (dead)

```

**Comment by Fuseteam** [comment] 2022-02-02 11:20
> How do I know if `EGL_PLATFORM=x11` is actually needed? I'm running Xorg. What does `EGL_PLATFORM` default to? Perhaps I need to configure something so that the default is usable?

Based on the output of `anbox session-manager` particularly this line:

```
 Failed to select EGL configuration
```
For whatever reason EGL is unable to set the platform correctly, so we set it manually with the enviroment variable. By setting it during runtime it is set for that particular process and only for that particular process

**Comment by Fuseteam** [comment] 2022-02-02 11:21
Hi @rmikedown do you still get that after running `systemctl start anbox-session-manager`?

**Comment by rmikedown** [comment] 2022-02-02 12:56
> Hi @rmikedown do you still get that after running `systemctl start anbox-session-manager`?

@Fuseteam Thanks for that. Actually, I ended up uninstalling and reinstalling, so I'm not on the latest version of anbox but it at least runs when I click on it. If I end up needing to update it then I'll test out your command.

**Comment by rakesh-rgb** [comment] 2022-03-08 02:39
I'm running Parrot os 4.11, with the 5.10 kernel. I ran into this issue as well. Here are my outputs for different 
commands, can anyone help me 
anbox launch --package=org.anbox.appmgr
[ 2022-03-08 02:15:52] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2022-03-08 02:15:52] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2022-03-08 02:15:52] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2022-03-08 02:16:03] [daemon.cpp:61@Run] [org.freedesktop.DBus.Error.ServiceUnknown] The name org.anbox was not provided by any .service files

and with EGL_PLATFORM=x11 anbox.appmgr, output is:

[ 2022-03-08 02:21:01] [launch.cpp:168@operator()] Session manager is not yet running, trying to start it
[ 2022-03-08 02:21:01] [launch.cpp:117@launch_session_manager] Started session manager, will now try to connect ..
[ 2022-03-08 02:21:01] [splash_screen.cpp:55@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2022-03-08 02:21:58] [launch.cpp:202@operator()] Session manager failed to become ready

**Comment by Fuseteam** [comment] 2022-03-08 13:05
@rakesh-rgb the command is `EGL_PLATFORM=x11 anbox session-manager` to start session manager, it "hanging" means it working correctly. if it is you can launch it via your desktop menu

**Comment by AndKe** [comment] 2022-04-09 12:30
My anbox worked fine a month ago or so.  (Ubuntu 21.10)
Today I discovered the issue in subject.
The ```EGL_PLATFORM=x11``` anbox session-manager trick kind of works.
usuually, the first attempt at anbox.manager fails with "Session manager failed to become ready"
- the other launch of anbox.manager works

How can I make it "just work" (start needed processes) without the workaround?

**Comment by Fuseteam** [comment] 2022-04-09 19:40
You can use my systemd user service to start session-manager automatically https://github.com/fuseteam/systemd-service-files

**Comment by AndKe** [comment] 2022-04-09 20:28
@Fuseteam I assume this means it will then start on every boot.
Is this a known issue that is expected to be fixed anytime soon?  (I'd rather have it start when needed, not always)

**Comment by Fuseteam** [comment] 2022-04-10 02:44
Yes it will start on every boot, no it's not known if it will be fixed.
You can skip the `systemctl --user enable anbox-session-manager` step if you don't want to start it on every boot.
You can then start it when, when you need it with `systemctl --user start anbox-session-manager`

**Comment by YSahil** [comment] 2022-05-17 03:50
@Fuseteam after running "`systemctl --user enable anbox-session-manager`" 
i got `Failed to enable unit: Unit file /home/sachin/.config/systemd/user/anbox-session-manager.service is masked.`

**Comment by Fuseteam** [comment] 2022-05-18 18:41
@YSahil huh that's odd, this info would've been useful on the other repo btw, i actually was just asking you for that output there xd

**Comment by K85** [comment] 2022-06-09 01:12
> @Fuseteam after running "`systemctl --user enable anbox-session-manager`" i got `Failed to enable unit: Unit file /home/sachin/.config/systemd/user/anbox-session-manager.service is masked.`

The same and i am in Ubuntu 22.04 LTS

**Comment by Fuseteam** [comment] 2022-06-09 01:20
@K85 i'm on Ubuntu 22.04 LTS too and it works, can you answer the questions i asked the other two over at https://github.com/fuseteam/systemd-service-files/issues/4?

**Comment by K85** [comment] 2022-06-09 02:13
> 

I once started the Anbox Simulator and every system-apps can be launch and work well.
but i have some trouble in installing third-party apps (maybe there are some problems in the .apk file itself)
so i change some of my config. currently, i can't launch anbox anymore and things get more strange.
i am going to un-install the anbox and start from scratch.
![image](https://user-images.githubusercontent.com/10484271/172749466-5ad79594-cb15-4634-88be-a728293e5a53.png)
![image](https://user-images.githubusercontent.com/10484271/172749539-1e20fbe5-a0fc-4046-959c-50f77b25b1b2.png)

**Comment by Kushagra-Srivastava** [comment] 2022-06-13 13:01
pls, start a new issue for individual problems.

**Closed** 2022-06-13 13:01 UTC
