### ISSUE TITLE
Adress already in use

### ISSUE THREAD

**Issue by janopae** [anbox/anbox#148] opened 2017-04-19 16:29 UTC
Hello everybody,
**Anbox release (`anbox version`) and system info (`anbox system-info`):**

my Anbox release is anbox 0.1.0 on Ubuntu, system info ist listed below.

**Description of the problem:**

When I start Anbox by anbox launch or by the icon in the launcher, nothing happens (Terminal says `[WW 2017-04-19 16:17:44] [launch.cpp:115@operator()] Stop waiting as we're already waiting for too long. Something is wrong
[WW 2017-04-19 16:17:44] [launch.cpp:116@operator()] with your setup and the container may have failed to boot. ` after a while.). When I type anbox session-manager, it says `[EE 2017-04-19 16:14:15] [daemon.cpp:58@Run] bind: Address already in use`. 

anbox container-manager says `[EE 2017-04-19 16:22:46] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"`. This bug has already been posted, but none of the solutions worked. Also, none of the other people having this bug also had the adress-in-use-thing. 

**Expected:**
I think, this could be handled by refreshing the android installation in a way. But how can I do this? I don't know much about the way Anbox works, but maybe you can help me?

**Additional info:**
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-lowlatency (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP PREEMPT Fri Mar 31 15:25:21 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Comment by morphis** [comment] 2017-04-20 05:19
`[EE 2017-04-19 16:14:15] [daemon.cpp:58@Run] bind: Address already in use.`

That simply says that you're running the session manager already and started it a second time. Not a bug.

`[EE 2017-04-19 16:22:46] [container_manager.cpp:90@setup_mounts] Android image does not exist at path "/var/lib/anbox/android.img"`

You need to tell the container manager where the android.img file is if it isn't available at `/var/lib/anbox/android.img`. You can use the `--android-image` parameter for that. For example

`$ anbox container-manager --android-image=/path/to/android.img`

What you describe as your real problem

`When I start Anbox by anbox launch or by the icon in the launcher, nothing happens`

was already stated in a number of other bugs. To make our life easier, can you see if there is another bug describing your problem? I am going to close this as this is a problem which is stated at least once by another bug.

**Closed** 2017-04-20 05:19 UTC
Labels: duplicate

**Comment by hub2git** [comment] 2017-04-25 18:36
@janopae, I think the bug (called "issue" in github) you want to follow is #40.

**Comment by janopae** [comment] 2017-06-03 14:46
Well, it still says "Adress already in use", after copying android.img to another path, telling anbox where to find it, the container manager running as root being the first command in the Terminal window after reboot... 

I don't think, this means the deamon is started twice. Or has it been started on startup by the init-system?

sudo anbox container-manager --android-image=/snap/anbox/x1/android.img
[sudo] Passwort für sascha: 
[EE 2017-06-03 14:40:10] [container_manager.cpp:76@operator()] bind: Address already in use

**Comment by elias-alea** [comment] 2018-01-12 12:29
Are you running this while the anbox application is running?
Try to stop the app first

**Comment by soshimee** [comment] 2021-11-10 10:33
Having the same problem, I think anbox doesn't fully quit sometimes and cause this.
