### ISSUE TITLE
Ubuntu Touch Nexus 5 = Anbox install kills wifi driver

### ISSUE THREAD

**Issue by BadAngelZ** [anbox/anbox#1261] opened 2019-10-12 17:48 UTC
I run the last ubuntu touch version (development 1194) on a Nexus 5 phone.
This problem was tested on two different nexus 5 phones: mine with some application and data inside, my wife's phone which does not have so much things in it.

Each time I upgrade my ubuntu, I must "re-install" anbox following this guide:
https://docs.ubports.com/en/latest/userguide/dailyuse/anbox.html
And it worked fine until last ubuntu upgrade ...

Since some ubuntu versions (~ 900), when flashing the bootloader, I got some strange behavior:
- camera "freezes" after taking a first shot. If I switch to front camera then to "standard" camera, the camera "unfreezes"
- enabling access points works sometimes, but fails often. As a workaround, I switch it on / off until it works.
- when the phone asks to be unlocked, the keyboard rises and forbids to type the code. The workaround: push the side button to shut off the screen then push it again to wake the phone up.

I precise: just after upgrading ubuntu touch: camera application and access point work great. But just after flashing anbox bootloader, those work strangely (as described).
The anbox bootloader is located here:
`http://cdimage.ubports.com/anbox-images/anbox-boot-$CODENAME.img`
with CODENAME="hammerhead"
Note: This file did not evolve since months (even if file date is 3rd august 2019).

Some days ago I upgraded my ubuntu touch from version 1162 to 1192. And after installing anbox bootloader, the wifi chip is no longer detected. Moreover, the NetworkManager uses 100% CPU making the phone really hot (workaround: shut it off, make it cool down, then reboot and remove some /etc/NetworkManager/ files, kill NetworkManager, then reboot again)

Previously I had version 1162, and it was fine (except that once bootloader being flashed I got the problems mentioned above, but I don't care about them because I do not use camera often, and workarounds are acceptable).
Now with versions from 1192 and above (1193), flashing the anbox bootloader removes the wifi "driver", and I must wait for the next build to be available to recover the wifi functionnality. Today, I got the 1194 ubuntu touch development version, but did not try to flash bootloader again (since I need my wifi connection, I will try again when the next version will be available, and I will have some spare time ;)

As suggested in [Hammerhead: r168 ubports-touch (16.04) can´t see wifi](https://github.com/ubports/ubuntu-touch/issues/414) I ran the following command:
`nmcli -p d`
It showed that wifi hardware was not detected.

Did I try to run anbox log collection ? No, because when my phone does not have wifi connection, so it's a pain to install anbox with the cell phone modem (since where I live, I do not have 3G/4G ... so download is ~ 11kB/s), so I could not install anbox:
```
sudo apt install anbox-ubuntu-touch
anbox-tool install
```
since it requires to download some Bytes ;)

**Please describe your problem:**

done :)

**What were you expecting?:**

Wifi being detected: even if the bootloader is not "corrected", a workaround would be fine :)

**Additional info:**

Once the next ubuntu image will be available, I will be able to collect more information by flashing the bootloader, so if you need them please just ask ! (admin sys skills available ;)

Thanks for your help !

**Comment by morphis** [comment] 2019-10-15 08:56
This is more a Ubports issue than an Anbox issue. @mariogrip any idea?

**Comment by BadAngelZ** [comment] 2019-10-15 09:40
Thanks for paying attention to my bug report.
I thought it was an "anbox" issue since it's the bootloader that triggers the problem.
You add the "invalid" flag to this bug, should I open this case on the ubuntu touch side ?
Regards,
Jerome

**Comment by gsantner** [comment] 2019-12-04 20:13
This issue and issue <https://github.com/anbox/anbox/issues/1261> <https://github.com/anbox/anbox/issues/1261>  seem to be duplicate of <https://github.com/ubports/ubuntu-touch/issues/1264> where a working solution is available from.
Do suggest to close this issue.

**Comment by BadAngelZ** [comment] 2019-12-04 22:10
Yes, once my phone was moved to the devel branch, anbox works again.
In bug "https://github.com/ubports/ubuntu-touch/issues/1264", I've read that the stable branch could work if the devel kernel be installed ... I tried to use the stable branch and flash only the "devel" kernel, but it didn't work (wifi disappeared). So I moved to the devel branch ...
By the way, there is no more need to "flash" the anbox kernel ... The wiki "http://docs.ubports.com/fr/latest/userguide/dailyuse/anbox.html" may be modified... May I help ?

**Comment by Xmas13** [comment] 2020-02-13 21:08
@BadAngelZ I highly agree, the wiki really needs to be updated as I got bit by this too and had to google around to find the solution. At the very least it should say, "Is broken, will be fixed in next OTA. If you are feeling brave, install the dev version and install using that."

**Comment by d0n601** [comment] 2020-05-04 18:41
@BadAngelZ @Xmas13 I was also bit by this, at this point the Wiki is pretty out of date as it's now months later.

**Comment by BadAngelZ** [comment] 2020-05-04 19:06
Still using the dev branch. To be honest I fear to upgrade my phone, because it works :)
For the note: I use anbox only for whatsapp (yes I've got colleagues that "needs" it ...)

**Closed** 2020-09-11 02:47 UTC
Labels: decaying, invalid
