### ISSUE TITLE
Anbox won't run 

### ISSUE THREAD

**Issue by MohamedxSalah** [anbox/anbox#375] opened 2017-07-20 09:26 UTC
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

** Please paste the result of `anbox system-info` below:**
```
version: 3
snap-revision: 44
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-28-generic (buildd@lgw01-11) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

```

**Please describe your problem:**

so i followed the instructions and installed anbox then when i try to open it it's hand on starting for a couple minutes then it close itself and when i try to open it again it's not opening at all

**What were you expecting?:**
i except it to work ! 

**Additional info:**
my device specs is 
amd e300 apu wth 8gb of ram 

i'm kinda of newbie to the linux world

**Comment by xtracerlabs** [comment] 2017-07-20 19:28
I have exactly the same issue.
Just don't want to create a duplicate topic, so let me leave my system-info too here, it might help possible:

```
anbox system-info
version: 3
snap-revision: 44
os:
  name: Ubuntu
  version: 17.04 (Zesty Zapus)
  snap-based: true
kernel:
  version: Linux version 4.10.0-28-generic (buildd@lgw01-11) (gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) ) #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Comment by david2896482** [comment] 2017-07-27 08:53
run the following command first and paste the output here

`ANBOX_LOG_LEVEL=debug anbox session-manager`

in another terminal run the following command

`adb logcat > ~/anbox_android.log`

upload the anbox_android.log in your home DIR here

**Comment by Pipeliner** [comment] 2017-08-06 22:47
@david2896482 followed your instructions, https://gist.github.com/Pipeliner/535953487514c4427285eb3424e6d2a5

```
version: 3
snap-revision: 47
os:
  name: Ubuntu
  version: 14.04.5 LTS, Trusty Tahr
  snap-based: true
kernel:
  version: Linux version 4.4.0-89-generic (buildd@lgw01-57) (gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) ) #112~14.04.1-Ubuntu SMP Tue Aug 1 22:08:32 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_swap_region
      - EGL_NOK_texture_from_pixmap
      - EGL_NV_post_sub_buffer
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES-CM 1.1 Mesa 17.0.7
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp
```

**Comment by david2896482** [comment] 2017-08-07 03:00
@Pipeliner 
The following might be the main problem.
But I dont know how to solve it.
Could you attach all necessary log and open a issue for it?
Attach the logcat's log, /var/log/syslog, /var/snap/anbox/common/logs/container.log and  /var/snap/anbox/common/data/system.log

`
08-06 22:41:27.801   477   477 E System  : ******************************************
08-06 22:41:27.801   477   477 E System  : ************ Failure starting system services
08-06 22:41:27.801   477   477 E System  : java.lang.RuntimeException: Failed to create service com.android.server.am.ActivityManagerService$Lifecycle: service constructor threw an exception
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:103)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:419)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.SystemServer.run(SystemServer.java:332)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.SystemServer.main(SystemServer.java:219)
08-06 22:41:27.801   477   477 E System  : 	at java.lang.reflect.Method.invoke(Native Method)
08-06 22:41:27.801   477   477 E System  : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-06 22:41:27.801   477   477 E System  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-06 22:41:27.801   477   477 E System  : Caused by: java.lang.reflect.InvocationTargetException
08-06 22:41:27.801   477   477 E System  : 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-06 22:41:27.801   477   477 E System  : 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:92)
08-06 22:41:27.801   477   477 E System  : 	... 6 more
08-06 22:41:27.801   477   477 E System  : Caused by: java.lang.IllegalArgumentException: Invalid argument: 477
08-06 22:41:27.801   477   477 E System  : 	at android.os.Process.setThreadGroup(Native Method)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.UiThread.<init>(UiThread.java:35)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.UiThread.ensureThreadLocked(UiThread.java:40)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.UiThread.get(UiThread.java:49)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.am.ActivityManagerService$UiHandler.<init>(ActivityManagerService.java:1607)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.am.ActivityManagerService.<init>(ActivityManagerService.java:2629)
08-06 22:41:27.801   477   477 E System  : 	at com.android.server.am.ActivityManagerService$Lifecycle.<init>(ActivityManagerService.java:2603)
08-06 22:41:27.801   477   477 E System  : 	... 9 more
08-06 22:41:27.801   477   477 D AndroidRuntime: Shutting down VM
08-06 22:41:27.801   477   477 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: main
08-06 22:41:27.801   477   477 E AndroidRuntime: java.lang.RuntimeException: Failed to create service com.android.server.am.ActivityManagerService$Lifecycle: service constructor threw an exception
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:103)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.SystemServer.startBootstrapServices(SystemServer.java:419)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.SystemServer.run(SystemServer.java:332)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.SystemServer.main(SystemServer.java:219)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
08-06 22:41:27.801   477   477 E AndroidRuntime: Caused by: java.lang.reflect.InvocationTargetException
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:92)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	... 6 more
08-06 22:41:27.801   477   477 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: Invalid argument: 477
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at android.os.Process.setThreadGroup(Native Method)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.UiThread.<init>(UiThread.java:35)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.UiThread.ensureThreadLocked(UiThread.java:40)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.UiThread.get(UiThread.java:49)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService$UiHandler.<init>(ActivityManagerService.java:1607)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.<init>(ActivityManagerService.java:2629)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService$Lifecycle.<init>(ActivityManagerService.java:2603)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	... 9 more
08-06 22:41:27.801   477   477 E AndroidRuntime: Error reporting crash
08-06 22:41:27.801   477   477 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActivityThread$Profiler.stopProfiling()' on a null object reference
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at android.app.ActivityThread.stopProfiling(ActivityThread.java:4867)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:93)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
08-06 22:41:27.801   477   477 E AndroidRuntime: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
08-06 22:41:27.801   477   477 I Process : Sending signal. PID: 477 SIG: 9
08-06 22:41:27.820    42    42 E         : eof
08-06 22:41:27.820    42    42 E         : failed to read size
08-06 22:41:27.820    42    42 I         : closing connection
08-06 22:41:27.820   447   447 E Zygote  : Exit zygote because system server (477) has terminated
`

**Closed** 2018-09-15 20:35 UTC
Labels: decaying
