### ISSUE TITLE
Raspbian/Buster DKMS add repository

### ISSUE THREAD

**Issue by Velarier** [anbox/anbox#1312] opened 2019-12-16 18:18 UTC
**Please describe your problem:**
pi@raspberrypi:~ $ sudo add-apt-repository ppa:morphis/anbox-support
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

**What were you expecting?:**
For the add repository to work, but it seems that something isn't implemented or missing in the git or my machine.

**Additional info:**
Had to use $ sudo apt-get install software-properties-common since it wasn't installed.
Raspberry 4 with 4Gb

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

This is a "Raspbian Buster with desktop and recommended software", kernel 4.19, after distr-upgrade.

**Comment by SupremeManggo** [comment] 2019-12-20 09:33
Anbox is available in Buster repository, and you don't need to install the kernel modules

**Comment by morphis** [comment] 2019-12-20 21:40
The PPA doesn't support Debian. Closing as not a bug.

**Closed by morphis** 2019-12-20 21:40 UTC
