### ISSUE TITLE
$ snap install --dangerous --devmode anbox_1_amd64.snap error: cannot open: "anbox_1_amd64.snap"

### ISSUE THREAD

**Issue by ali-aryan** [anbox/anbox#786] opened 2018-07-02 13:51 UTC
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues
2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`
3. Make sure you have debug logs enabled:
`sudo snap set anbox debug.enable=true`
4. Reproduce the error while debug logs enabled.
5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

6. ** Please paste the result of `anbox system-info` below:**
```
[please paste printout of `anbox system-info` here]
```

**Please describe your problem:**

**What were you expecting?:**

**Additional info:**

**Comment by morphis** [comment] 2018-07-02 13:55
Closing this as a duplicate of #785

**Closed by morphis** 2018-07-02 13:55 UTC
