### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by vamur** [anbox/anbox#109] opened 2017-04-15 14:06 UTC
Currently on Archlinux weston running session-manager fails even though wayland supports EGL.

> SDL_VIDEODRIVER=wayland ANBOX_LOG_LEVEL=debug anbox session-manager --gles-driver=host

> [Renderer.cpp:105@initialize] Failed to initialize EGL

**Comment by JackHack96** [comment] 2017-04-16 18:33
Possible duplicate of #11

**Comment by morphis** [comment] 2017-04-19 05:32
We're not specific to any display sever protocol as we're using SDL which already has support for wayland. This needs someone looking at a wayland desktop and check if we need a more recent SDL version to make this working.

**Comment by morphis** [comment] 2017-04-20 05:16
@vamur Correct, missing support for EGL pbuffers is the current problem for wayland/mir. However this doesn't include Android devices as their drivers ship pbuffer support and if you run Anbox on top of that everything is fine. What is affected by this are desktop-type devices.

The way forward to workaround this, is to use the surfaceless platform of Mesa to be able to still use pbuffers for the offscreen rendering we're doing. Alternatively we could use FBO's to render but I am not yet clear how that would look like with the rest of the code we have. All in all this needs refactoring of the existing Renderer code in multiple ways.

**Comment by morphis** [comment] 2017-04-26 06:29
https://github.com/anbox/anbox/pull/189 contributes to this as it ensures all necessary environment variables are available for services launched by the `systemd --user` instance.

**Closed** 2018-03-14 16:42 UTC
Labels: enhancement, help wanted
