### ISSUE TITLE
Anbox not opening/starting

### ISSUE THREAD

**Issue by daavm** [anbox/anbox#23] opened 2017-04-11 22:51 UTC
Make sure you are running the latest version of Anbox before reporting an issue.

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
anbox 0.1.0
------
INFO
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-72-generic (buildd@lcy01-17) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a

**Description of the problem:**
It doesn't start, and the whole system becomes laggy when it's "started". 

**Expected:**
I would say... I expect it to start? 

**Additional info:**
-- anbox session-manager returns the following:
[EE 2017-04-11 22:49:41] [Renderer.cpp:100@initialize] Failed to Initialize backend EGL display
Segmentation fault (core dumped)

**Comment by ric96** [comment] 2017-04-12 00:54
same with nvidia gpu and proprietary drivers.

**Comment by userj** [comment] 2017-04-13 00:04
> same with nvidia gpu and proprietary drivers.

Same here.

**Comment by Pillar1989** [comment] 2017-04-13 09:14
Same here.

**Comment by freundTech** [comment] 2017-04-14 10:06
Duplicate of #11 I think.

**Comment by morphis** [comment] 2017-04-21 05:25
The original issue  described here is because we don't support the Nvidia driver yet. Duplicate of https://github.com/anbox/anbox/issues/11

**Closed by morphis** 2017-04-21 05:25 UTC
