### ISSUE TITLE
Anbox not start in ubuntu 18.04 with any kernel

### ISSUE THREAD

**Issue by trprado** [anbox/anbox#879] opened 2018-08-23 19:59 UTC
1. Please check that no similar bug is already reported. Have a look on the list of open bugs at https://github.com/anbox/anbox/issues

2. Make sure you are running the latest version of Anbox before reporting an issue. Update snap to latest: `snap refresh --devmode --edge anbox`

snap "anbox" has no updates available

3. Make sure you have debug logs enabled:
 `sudo snap set anbox debug.enable=true`

4. Reproduce the error while debug logs enabled.
```
$ anbox.appmgr 
/snap/anbox/143/bin/desktop-launch: line 160: de: command not found
[ 2018-08-23 19:46:29] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2018-08-23 19:46:29] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
/usr/share/libdrm/amdgpu.ids: No such file or directory
[ 2018-08-23 19:46:29] [splash_screen.cpp:50@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2018-08-23 19:47:19] [launch.cpp:214@operator()] Session manager failed to become ready
```

5. Run the anbox logs collection utility and attach the tar file.
`sudo /snap/bin/anbox.collect-bug-info `

[anbox-system-diagnostics-2018-08-23.zip](https://github.com/anbox/anbox/files/2315947/anbox-system-diagnostics-2018-08-23.zip)

6. ** Please paste the result of `anbox system-info` below:**
```
$ anbox system-info
/snap/anbox/143/bin/desktop-launch: line 160: de: command not found
/usr/share/libdrm/amdgpu.ids: No such file or directory
version: 4
snap-revision: 143
cpu:
  arch:  x86
  brand: AMD Phenom(tm) II X4 945 Processor
  features: 
os:
  name: Ubuntu
  version: 18.04.1 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.18.3-041803-generic (kernel@gloin) (gcc version 8.2.0 (Ubuntu 8.2.0-4ubuntu1)) #201808180530 SMP Sat Aug 18 09:32:58 UTC 2018
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.5 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_KHR_cl_event2
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: X.Org
    vendor: OpenGL ES 3.1 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_base_instance
      - GL_EXT_blend_func_extended
      - GL_EXT_blend_minmax
      - GL_EXT_buffer_storage
      - GL_EXT_clip_cull_distance
      - GL_EXT_color_buffer_float
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_copy_image
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_geometry_point_size
      - GL_EXT_geometry_shader
      - GL_EXT_gpu_shader5
      - GL_EXT_map_buffer_range
      - GL_EXT_memory_object
      - GL_EXT_memory_object_fd
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_primitive_bounding_box
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_integer_mix
      - GL_EXT_shader_io_blocks
      - GL_EXT_tessellation_point_size
      - GL_EXT_tessellation_shader
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_buffer
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_cube_map_array
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_sRGB_decode
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robust_buffer_access_behavior
      - GL_KHR_robustness
      - GL_MESA_shader_integer_functions
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_image_formats
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_copy_image
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_depth_texture_cube_map
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_geometry_point_size
      - GL_OES_geometry_shader
      - GL_OES_get_program_binary
      - GL_OES_gpu_shader5
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_primitive_bounding_box
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_image_atomic
      - GL_OES_shader_io_blocks
      - GL_OES_shader_multisample_interpolation
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_tessellation_point_size
      - GL_OES_tessellation_shader
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_buffer
      - GL_OES_texture_cube_map_array
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_texture_stencil8
      - GL_OES_texture_storage_multisample_2d_array
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float
      - GL_OES_viewport_array
```

**Please describe your problem:**
Anbox not start.

**What were you expecting?:**
Anbox start window and not stop to work.

**Additional info:**
kernel:
Linux dev-desk-ubuntu 4.18.3-041803-generic #201808180530 SMP Sat Aug 18 09:32:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
I try with original generic kernel 4.15.x x64, generic kernel 4.17.x x64 and generic kernel 4.18.3 x64.

**Comment by WPFilmmaker** [comment] 2018-08-25 13:55
On my System (Lubuntu 16.04) the latest beta as August 25, and anbox (edge) 4-7cc6fb4 (on virtualized Lubuntu 18.04, I updated `withsnap refresh --devmode --edge anbox)` work. Maybe try to update?

**Comment by trprado** [comment] 2018-08-26 15:55
No work

```
$ snap refresh --devmode --edge anbox
snap "anbox" has no updates available
$ anbox.appmgr 
/snap/anbox/143/bin/desktop-launch: line 160: de: command not found
[ 2018-08-26 15:53:17] [launch.cpp:182@operator()] Session manager is not yet running, trying to start it
[ 2018-08-26 15:53:17] [launch.cpp:116@launch_session_manager] Started session manager, will now try to connect ..
/usr/share/libdrm/amdgpu.ids: No such file or directory
[ 2018-08-26 15:53:20] [splash_screen.cpp:50@SplashScreen] Window has no associated renderer yet, creating one ...
[ 2018-08-26 15:54:11] [launch.cpp:214@operator()] Session manager failed to become ready
```

**Comment by victorzhuk** [comment] 2018-08-27 12:16
Have same error while start app in Archlinux, "[launch.cpp:214@operator()] Session manager failed to become ready". Try start session manually and listen dbus, session console empty, dbus send back ready=false

**Comment by morphis** [comment] 2018-09-02 12:04
This is another incarnation of the bug reports where the Android init process crashes after ~1 second

```
lxc 20180823194629.807 TRACE    lxc_start - start.c:lxc_serve_state_socket_pair:501 - Sent container state "RUNNING" to 14
lxc 20180823194629.807 TRACE    lxc_start - start.c:lxc_serve_state_clients:429 - Set container state to RUNNING
lxc 20180823194629.807 TRACE    lxc_start - start.c:lxc_serve_state_clients:432 - No state clients registered
lxc 20180823194629.807 DEBUG    lxc_container - lxccontainer.c:wait_on_daemonized_start:822 - First child 6582 exited
lxc 20180823194629.807 TRACE    lxc_container - lxccontainer.c:wait_on_daemonized_start:838 - Container is in "RUNNING" state
lxc 20180823194629.807 TRACE    lxc_start - start.c:lxc_poll:587 - Mainloop is ready
lxc 20180823194629.807 NOTICE   lxc_start - start.c:signal_handler:399 - Received 17 from pid 6585 instead of container init 6584
lxc 20180823194630.413 DEBUG    lxc_start - start.c:signal_handler:411 - Container init process 6584 exited
lxc 20180823194630.413 TRACE    lxc_start - start.c:lxc_poll:601 - Closed console mainloop
lxc 20180823194630.413 TRACE    lxc_start - start.c:lxc_poll:606 - Closed mainloop
lxc 20180823194630.413 TRACE    lxc_start - start.c:lxc_poll:610 - Closed signal file descriptor 3
lxc 20180823194630.413 DEBUG    lxc_start - start.c:__lxc_start:1930 - Unknown exit status for container "default" init 4
```

Also 

```
$ anbox.appmgr 
/snap/anbox/143/bin/desktop-launch: line 160: de: command not found
```

Indicates that the snap desktop launch helper still don't work well with i18n (see https://github.com/ubuntu/snapcraft-desktop-helpers/issues/131)

The other thing is the CPU (AMD Phenom(tm) II X4 945 Processor) your using. From https://en.wikipedia.org/wiki/Phenom_II we can see that it misses support for SSSE 3 which is mandatory for the Android system image currently being used by Anbox. See #499 for more details. Effectively I would like to close this as a duplicate of #499 now but wondering how you installed Anbox.

`snap install --edge --devmode` should now abort the installation if it detects a not support CPU. I guess you installed via `snap install --beta --devmode` and then refreshed manually to edge via `snap refresh --edge --devmode anbox`. @trprado Can you confirm that?

**Comment by gshmu** [comment] 2018-09-02 13:34
mac Vbox Ubuntu 18.04 iso.
 Failed to connect to DBus.

**Comment by trprado** [comment] 2018-09-02 16:44
Its possible that the problem is really the SSSE3 instruction, the phenom ii x4 945 not have this instruction. This instruction is more new than my processor. =(

**Comment by morphis** [comment] 2018-09-07 21:57
@EugeneKorneev We do not support 32-bit systems. However that doesn't prevent anybody from building both Android and Anbox for 32 bit systems but the upstream project will not do that.

**Comment by morphis** [comment] 2018-09-07 21:57
Closing this as the cause for the bug are the missing instructions on the used CPU.

**Closed by morphis** 2018-09-07 21:57 UTC
Labels: needs-info

**Comment by nightman19** [comment] 2019-05-12 02:19
My anbox crashes after trying to start.

#anbox system-info
version: 4
snap-revision: 176
cpu:
  arch:  x86
  brand: Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
  features: 
    - aes
os:
  name: Ubuntu
  version: 18.04.2 LTS (Bionic Beaver)
  snap-based: true
kernel:
  version: Linux version 4.18.0-17-generic (buildd@lgw01-amd64-021) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 2.0 Mesa 18.0.5
    extensions:
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_APPLE_texture_max_level
      - GL_EXT_blend_minmax
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_discard_framebuffer
      - GL_EXT_draw_buffers
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_frag_depth
      - GL_EXT_map_buffer_range
      - GL_EXT_multi_draw_arrays
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_read_format_bgra
      - GL_EXT_robustness
      - GL_EXT_separate_shader_objects
      - GL_EXT_texture_border_clamp
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_format_BGRA8888
      - GL_EXT_texture_rg
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_EXT_unpack_subimage
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_KHR_debug
      - GL_KHR_no_error
      - GL_KHR_robustness
      - GL_NV_draw_buffers
      - GL_NV_fbo_color_attachments
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_OES_EGL_image
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_depth_texture
      - GL_OES_draw_elements_base_vertex
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_get_program_binary
      - GL_OES_mapbuffer
      - GL_OES_packed_depth_stencil
      - GL_OES_required_internalformat
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_surfaceless_context
      - GL_OES_texture_3D
      - GL_OES_texture_border_clamp
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_array_object
      - GL_OES_vertex_half_float

**Comment by JohnAdmas** [comment] 2019-09-21 20:04
you have to manually load the kernel modules. The next time your
system starts they will be automatically loaded.

$ sudo modprobe ashmem_linux
$ sudo modprobe binder_linux

Now you should have two new nodes in your systems /dev directory:
$ ls -l /dev/{ashmem,binder}

/dev/ashmem
/dev/binder

it works, for me

**Comment by krzydoug** [comment] 2020-10-06 22:01
[This](https://superuser.com/a/1590708/511639) answer resolved the issue for me on Ubuntu 20.04

**Comment by agumaronald** [comment] 2021-09-02 13:17
anbox system-info
version: 0.0~git20210106-1-Debian
cpu:
  arch:  x86
  brand:        Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
  features: 
    - aes
    - sse4_1
    - sse4_2
    - avx
os:
  name: Parrot OS
  version: 4.11
  snap-based: false
kernel:
  version: Linux version 5.10.0-8parrot1-amd64 (team@parrotsec.org) (gcc-10 (Debian 10.2.1-6) 10.2.1 20210110, GNU ld (GNU Binutils for Debian) 2.35.2) #1 SMP Debian 5.10.46-8parrot1 (2021-07-21)
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4
    extensions:
      - EGL_ANDROID_blob_cache
      - EGL_ANDROID_native_fence_sync
      - EGL_CHROMIUM_sync_control
      - EGL_EXT_buffer_age
      - EGL_EXT_create_context_robustness
      - EGL_EXT_image_dma_buf_import
      - EGL_EXT_image_dma_buf_import_modifiers
      - EGL_EXT_swap_buffers_with_damage
      - EGL_KHR_config_attribs
      - EGL_KHR_create_context
      - EGL_KHR_create_context_no_error
      - EGL_KHR_fence_sync
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_gl_renderbuffer_image
      - EGL_KHR_gl_texture_2D_image
      - EGL_KHR_gl_texture_3D_image
      - EGL_KHR_gl_texture_cubemap_image
      - EGL_KHR_image
      - EGL_KHR_image_base
      - EGL_KHR_image_pixmap
      - EGL_KHR_no_config_context
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_KHR_swap_buffers_with_damage
      - EGL_EXT_pixel_format_float
      - EGL_KHR_wait_sync
      - EGL_MESA_configless_context
      - EGL_MESA_drm_image
      - EGL_MESA_image_dma_buf_export
      - EGL_MESA_query_driver
      - EGL_NOK_texture_from_pixmap
      - EGL_WL_bind_wayland_display
  gles2:
    vendor: Intel Open Source Technology Center
    vendor: OpenGL ES 3.0 Mesa 20.3.5
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_filter_anisotropic
      - GL_EXT_texture_compression_s3tc
      - GL_EXT_texture_compression_dxt1
      - GL_EXT_texture_compression_rgtc
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_standard_derivatives
      - GL_OES_stencil8
      - GL_OES_texture_3D
      - GL_OES_texture_float
      - GL_OES_texture_float_linear
      - GL_OES_texture_half_float
      - GL_OES_texture_half_float_linear
      - GL_OES_texture_npot
      - GL_OES_vertex_half_float
      - GL_EXT_draw_instanced
      - GL_EXT_texture_sRGB_decode
      - GL_OES_EGL_image
      - GL_OES_depth_texture
      - GL_OES_packed_depth_stencil
      - GL_EXT_texture_type_2_10_10_10_REV
      - GL_NV_conditional_render
      - GL_OES_get_program_binary
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_EXT_frag_depth
      - GL_NV_fbo_color_attachments
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_pack_reverse_row_order
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_occlusion_query_boolean
      - GL_EXT_robustness
      - GL_EXT_texture_rg
      - GL_EXT_unpack_subimage
      - GL_NV_draw_buffers
      - GL_NV_read_buffer
      - GL_NV_read_depth
      - GL_NV_read_depth_stencil
      - GL_NV_read_stencil
      - GL_EXT_draw_buffers
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_KHR_robustness
      - GL_NV_pixel_buffer_object
      - GL_OES_depth_texture_cube_map
      - GL_OES_required_internalformat
      - GL_OES_surfaceless_context
      - GL_EXT_color_buffer_float
      - GL_EXT_sRGB_write_control
      - GL_EXT_separate_shader_objects
      - GL_EXT_shader_group_vote
      - GL_EXT_shader_integer_mix
      - GL_INTEL_performance_query
      - GL_EXT_base_instance
      - GL_EXT_compressed_ETC1_RGB8_sub_texture
      - GL_EXT_draw_buffers_indexed
      - GL_EXT_draw_elements_base_vertex
      - GL_EXT_polygon_offset_clamp
      - GL_EXT_texture_border_clamp
      - GL_KHR_blend_equation_advanced
      - GL_KHR_context_flush_control
      - GL_OES_draw_buffers_indexed
      - GL_OES_draw_elements_base_vertex
      - GL_OES_sample_shading
      - GL_OES_sample_variables
      - GL_OES_shader_multisample_interpolation
      - GL_OES_texture_border_clamp
      - GL_EXT_blend_func_extended
      - GL_EXT_float_blend
      - GL_KHR_no_error
      - GL_OES_EGL_image_external_essl3
      - GL_EXT_clip_cull_distance
      - GL_EXT_disjoint_timer_query
      - GL_EXT_texture_compression_s3tc_srgb
      - GL_MESA_shader_integer_functions
      - GL_EXT_clip_control
      - GL_KHR_parallel_shader_compile
      - GL_EXT_EGL_image_storage
      - GL_EXT_shader_framebuffer_fetch_non_coherent
      - GL_EXT_texture_sRGB_R8
      - GL_EXT_texture_shadow_lod
      - GL_INTEL_blackhole_render
      - GL_MESA_framebuffer_flip_y
      - GL_EXT_demote_to_helper_invocation
      - GL_EXT_depth_clamp
      - GL_EXT_texture_query_lod

**Comment by Fuseteam** [comment] 2021-09-03 17:24
@agumaronald that seems fine, what appears to be the issue?
