### ISSUE TITLE
unsupported distribution

### ISSUE THREAD

**Issue by crusher42** [anbox/anbox#421] opened 2017-08-24 00:18 UTC
i use `./anbox-installer` on solus
and i get this 

> Anbox (Android in a Box) - Installer

IMPORTANT: THIS IS ALPHA LEVEL SOFTWARE. EXPECT INSTABILITY AND
           BUGS !!!!!

IMPORTANT: ALSO PLEASE BE AWARE THAT WE DON'T PROVIDE FULL
           CONFINEMENT FOR THE SNAP YET !!!!

PLEASE NOTE: This script will require root access on your system
to install all necessary things. It will prompt you to enter your
password when required.

ERROR: You are running the installer on an unsupported distribution.
       At the moment we only support the following distributions:

Ubuntu, LinuxMint, neon, elementary, Zorin

If your distribution is in the list but you still see this message, open
an issue here: https://github.com/anbox/anbox-installer

**Comment by bram209** [comment] 2017-08-25 09:38
Duplicate of #409

**Closed** 2018-09-15 20:36 UTC
Labels: decaying
