### ISSUE TITLE
Unable to open quota2 logging socket.. and zygote crashed

### ISSUE THREAD

**Issue by david2896482** [anbox/anbox#371] opened 2017-07-19 06:42 UTC
**Please paste the result of `anbox system-info` below:**
```
https://pastebin.com/SJWkJT3Y
```

**Please describe your problem:**
```
The anbox seems like booting into a loop.
Here is the Logcat's message.
Zygote init failed, and Netd died.
Netd Start ,but the socket protocol not supported.
Zygote init failed, and Netd died.
Keep looping....
```
```
a part of system.log
https://pastebin.com/YHVJ3uq2
```
**What were you expecting?:**
```
Solve the problem, and boot up successfully
Maybe you can tell us, what is the platform you boot up anbox successfully
```
**Additional info:**
```
syslog:
https://pastebin.com/zJ3xqsWL
```
```
system.log under .../common/data directory
https://gist.github.com/david2896482/4478299d360d23aa95d3e871c129c8ea
```
```
container.log under ..../common/data
https://gist.github.com/david2896482/47e7179a83fd466e3b0e830cf2428da4
```
**ifconfig:**
```
eth0      Link encap:Ethernet  HWaddr 3e:cc:fd:fb:63:b9
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0 
          inet6 addr: fe80::3ccc:fdff:fefb:63b9/64 Scope: Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:52 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:15 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:7080 TX bytes:1146 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0 
          inet6 addr: ::1/128 Scope: Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:4 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:248 TX bytes:248 
```

**Comment by david2896482** [comment] 2017-07-19 07:49
BTW, Could you release an ext4-formatted android image?
Because the squhfs is a read-only file system.
I cant do any modify on it

**Comment by morphis** [comment] 2017-07-22 14:37
> BTW, Could you release an ext4-formatted android image?
Because the squhfs is a read-only file system.
I cant do any modify on it

That is not true. You can easily do that by uncompressing the squashfs image, packing it again and bind mounting it over /snap/anbox/current/anbox.img and finally restarting the container manager.

If you do this, we wont give you any further support as we only have control over what ends up in the android.img we ship and otherwise end up in debugging scenarios in a complex environment we can't control or reproduce.

**Comment by morphis** [comment] 2017-07-22 14:39
The problem with the container you're experiencing is because of a bug in snapd (https://snapcraft.io). The current core snap in the stable channel (revision 2381) incorrectly enables seccomp for devmode snaps. You can switch to the version in candidate (`snap refresh --candidate core`) or wait a few days until the new version shows up in stable.

Closing this as not being a bug inside Anbox.

**Closed by morphis** 2017-07-22 14:39 UTC

**Comment by david2896482** [comment] 2017-07-26 02:01
Okay thanks!!
It really helps!
I and my partner were asked to study it ,and we may write a paper about android virtualization based on anbox's way(container, emulator..., etc)

**Comment by david2896482** [comment] 2017-08-21 08:01
@morphis Hi, I have this problem again.
Could you help me?
Bug log : https://drive.google.com/open?id=0Bx4wFQrz8nAAczk1TUhMRk9xY00
Should I open a new issue?
```
snap info core
name:      core
summary:   "snapd runtime environment"
publisher: canonical
description: |
  The core runtime environment for snapd
type:        core
snap-id:     99T7MUlRhtI3U0QFgl5mXXESAiSwt776
tracking:    candidate
installed:   16-2.27.2 (2677) 85MB core,devmode
refreshed:   2017-08-16 21:21:08 +0800 CST
channels:                      
  stable:    16-2.26.14 (2462) 84MB -
  candidate: 16-2.27.2  (2677) 85MB -
  beta:      16-2.27.2  (2677) 85MB -
  edge:      16-2.27.2  (2708) 85MB -

```
