### ISSUE TITLE
anbox launch with error

### ISSUE THREAD

**Issue by Kuanghusing** [anbox/anbox#93] opened 2017-04-14 08:56 UTC
**Anbox release (`anbox version`) and system info (`anbox system-info`):**
version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.4.0-53-generic (buildd@lcy01-28) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: n/a
    version: n/a
    extensions: []
  gles2:
    vendor: n/a
    vendor: n/a
    extensions: []

**Description of the problem:**
➜  ~ /snap/bin/anbox session-manager
[EE 2017-04-14 08:53:54] [Renderer.cpp:100@initialize] Failed to Initialize backend EGL display
[1]    3642 segmentation fault  /snap/bin/anbox session-manager

**Expected:**

**Additional info:**

**Comment by freundTech** [comment] 2017-04-14 10:03
Duplicate of #11

**Comment by Kuanghusing** [comment] 2017-04-14 10:05
i solve the problem
just change the GPU from NVIDIA to Intel
it seems it has problem with the NVIDIA driver
then reboot
/snap/bin/anbox session-manager (do not close the teminal)
start anbox from the menu

**Closed** 2018-09-15 22:35 UTC
Labels: decaying
